# Generated by Django 4.2 on 2023-04-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_winequality_lr_pred_alter_winequality_quality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winequality',
            options={'verbose_name': 'Wine Quality', 'verbose_name_plural': 'Wine Quality'},
        ),
    ]
