# Generated by Django 4.2 on 2023-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_winequality_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='winequality',
            name='rf_pred',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winequality',
            name='svm_pred',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
